[package]
name = "rtsp_stream_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
rfd = "0.14.1"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
m3u8-rs = "5.0.4"
tempfile = "3.8.0"
chrono = "0.4"
opencv = "0.93.5"
